mybatis:
    type-aliases-package: com.holddie.mybatisdruid.entity
spring:
    datasource:
        druid:
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 2000
            initial-size: 3
            max-active: 10
            max-wait: 60000
            min-idle: 3
            one:
                driverClassName: com.mysql.jdbc.Driver
                max-active: 20
                max-wait: 10000
                password: 123456
                url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false
                username: root
            stat-view-servlet:
                login-password: admin
                login-username: admin
            two:
                driverClassName: com.mysql.jdbc.Driver
                max-active: 30
                max-wait: 20000
                password: 123456
                url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8&useSSL=false
                username: root
    redis:
      database: 0
      host: 10.15.0.219
      port: 6380
      password:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 10000
